### ISSUE TITLE
small subsection of event item is pressable

### ISSUE THREAD

**Issue by sam1463** [joshjhargreaves/react-native-event-calendar#18]
The style for the `<View>` component used to render event items is calculated separately from the style for the `<TouchableOpacity>` component used to make the event handle touches, so as a result, parts of the view don't respond to presses. It would be pretty helpful to allow the entire visible area to be touchable, for a more intuitive user experience. Not sure if it's just a matter of making the entire view a touchable component instead (rather than view with a touchable as a child), or whether that would have bad side-effects. This could also be added with a new prop for whether to make the entire component touchable or not (so that current functionality wouldn't be altered, unless that prop was specified). Happy to open a PR if this would be ok.

**Comment by joshjhargreaves** [comment]
@sam1463 thanks for opening the issue! I actually had noticed this myself, this was a subtle recent regression. 

You’re right, I think the whole view should be touchable. While changing this to be the default would technically alter functionality, I think this is definitely the expected behaviour, so adding a prop for it would be necessary I don’t think. Happy to merge a PR if you open one! Or make the change myself when I have a bit of time in the next couple of days. I also want to address a performance issue with swiping left and right which hopefully will add some value!

**Comment by sam1463** [comment]
Cool, I'll try to open a PR when I have time.

**Comment by joshjhargreaves** [comment]
Fixed in: https://github.com/joshjhargreaves/react-native-event-calendar/pull/21
